services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: node server.js
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --port 27017 --bind_ip_all --tlsMode disabled
    volumes:
      - ./mongo:/data/db